services:
  mongo:
    image: "mongo:4.4-bionic"
    restart: always
  backend:
    depends_on:
      - mongo
    build: ./backend
    ports:
      - "8080:80"
  frontend:
    depends_on:
      - backend
    build: .
    ports:
      - "3000:3000"
